### ISSUE TITLE
Error when running API_ROS_KUKA_V30032017 on lbr?

### ISSUE THREAD

**Issue by eric-tc** [jonaitken/KUKA-IIWA-API#1]
Hi,

thanks for sharing the code but when i run the application in the robot controller i get "No controller with given name 'KUKA_Sunrise_Cabinet_1' known".
Where i can find the exact name. I'am using the Lbr iiwa 7 r800 with the sunrise 1.14.1.15 version.

Thanks

**Comment by eric-tc** [comment]
I have found a solution by commenting line 80:  getController("KUKA_Sunsrise_Cabinet_1"). Is this could be a problem?

Thanks,
Eric

**Comment by jonaitken** [comment]
Possibly re-sync the controller file to Sunrise. The command needed to setup the controller; I've not seen this before, and we've run on an iiwa 7 and 14 with the same code. Possibly try restarting the cabinet too.

@saeidmokaram  did you see this switching between different robot versions?

**Comment by eric-tc** [comment]
Hi thanks for the answer. Unfortunately after restarting and re-sync the problem persist. I have found a solution by changing line 80 with "getContext.getDefaultController()". Do you think could be a solution?

Thanks

**Comment by jonaitken** [comment]
Agreed, I think that should be appropriate as it's the context that supplies the controller that we were looking for by name. If that connects and presents the data and enables control on the computer side then that would be a solution!

**Comment by eric-tc** [comment]
Ok everything is working. I'm gonna close this. Thanks a lot for your support and your work.
