### ISSUE TITLE
Feedback control of robot moves

### ISSUE THREAD

**Issue by eric-tc** [jonaitken/KUKA-IIWA-API#2]
Hi,

there is a way to understand when the robot has stopped to move before execute the next python command.
for example:

my_client.send_command()
print("1")

i want to print "1" only when the robot stops.

Thanks

**Comment by jonaitken** [comment]
Typically when I've used the code I've implemented a small check outside of our code to check position; effectively I write a waitForCompletion method, which just looks at the error in demand position to a certain tolerance, and blocks until ready (this worked best for some of the applications I was using as I had some extra services which were providing different functionality which needed to be kept informed). There are neater ways of doing it, but for the moment we've not coupled this feedback into the API directly - though it's implicit from feedback on the topic channels e.g. current velocities etc.
