### ISSUE TITLE
Possible Fastest communication

### ISSUE THREAD

**Issue by robotgradient** [jonaitken/KUKA-IIWA-API#4]
Hi,

I am reading your API and I have seen you are doing a 100ms sleep each cycle.

I would like to know which was the fastest communication you got with this API.

Bests,

Julen U.

**Comment by jonaitken** [comment]
Morning,

Sorry to take some time! I'm not 100% certain how quick we've pushed it, this could probably be reduced, however, I believe on mode change there's a 100ms pause inbuilt, this shouldn't play any part on the read data though, so I suspect it could be reduced!
