### ISSUE TITLE
Simulator for the KUKA-IIWA-API

### ISSUE THREAD

**Issue by matteopantano** [jonaitken/KUKA-IIWA-API#7]
Hi,

I am investigating the usage of a simulator with the API. Has been some work already done? I have seen that V-REP simulation engine could be an option, any hint on how to start with it?
Thanks.

Kind Regards,

Matteo

**Comment by jonaitken** [comment]
Hi Matteo,

My apologies for not getting back in touch sooner. We're working on a number of things here, especially looking at what simulation engineers we could plug in. We have some things in development but they aren't ready for release yet. In general the API will report the conditions of the robot (it's more of a flexible programming interface to enable us to easily code what we need and expand functionality/capability as we require), for that reason it provide the dynamics or kinematic solutions that you might want for a simulation. Obviously if you've got an iiwa on the bench it can provide that functionality!

In general it would be worth also looking at some of the Ros Industrial packages which do provide some of this information which might make it a little easier to plug into V-REP.

Best wishes,
Jonathan

**Comment by matteopantano** [comment]
Hi Jonathan,

I have investigated several simulator engines like robodk, kuka simulator, V-REP, ROS etc.. However, as final decision I have opted to use the real robot with appropriate joint limits.

BR, 

Matteo

**Comment by jonaitken** [comment]
Thank you!
