### ISSUE TITLE
Socket communication timeout

### ISSUE THREAD

**Issue by matteopantano** [jonaitken/KUKA-IIWA-API#8]
To whom it may concern,

I am trying to run the java application on the KUKA but I am keep getting connection timeout. My python server is running and I have tested it via connecting via another device, but seems KUKA cannot connect.

Is there a conf step that I have missed?

Thanks

BR,

Matteo

**Comment by jonaitken** [comment]
Hi Matteo,

I’ve seen this a couple of times, usually it’s startup order. Check that you can ping the Kuka cabinet from the pc, then on startup start the server before launching the app on the pendant. It should connect on app start. If it doesn’t, it’s worth rebooting. Please let me know if there’s any problem!

Best wishes 
Jonathan

**Comment by matteopantano** [comment]
Hi Jonathan,

I have done as you said. The laptop can ping the controller and I can also upload the code so the connection is running. However, seems that the server does not go through the `sock.accept()`

Down below the wireshark capture:

![connection_issue_iiwa](https://user-images.githubusercontent.com/26014548/56266452-86b3f600-60ec-11e9-920b-82bf9c800082.PNG)

Seems that the IP is resolved but the PC in some way does not reply.

BR,

Matteo


Edit:

KUKA IP: 172.31.1.147
PC IP: 172.31.1.50

**Comment by matteopantano** [comment]
Solved, it was a problem with firewall rules.

For the sake of clarity someone should or disable firewall or create an inbound policy that allows communication from iiwa port to the port of the laptop.

**Comment by jonaitken** [comment]
Excellent m thank you for letting us know!
