### ISSUE TITLE
Cannot run roscore and node at the same time

### ISSUE THREAD

**Issue by Leytha** [jonaitken/KUKA-IIWA-API#9]
Hi,
I'm having some troubles running your API. I have followed the configuration instructions, and right now the API_ROS_KUKA_V30032017 application appears in the SmartPad, and I have the kuka_controller folder inside my catkin_ws. I haven't changed the IP provided as an example, so my net has two devices connected: 

1.  The IIWA robot with IP 172.31.1.147 
2.  My Ubuntu laptop with IP 172.31.1.50. 

In my Ubuntu laptop I have changed the ```.bashrc``` and added:
``` 
export ROS_IP=172.31.1.50
export ROS_MASTER_URI=http://$ROS_IP:1234
esport ROS_WORKSPACE=/home/myuser/catkin_ws

source /opt/ros/indigo/setup.bash
source ~/catkin_ws/devel/setup.bash
```
I'm using ROS Indigo but for the moment I haven't had any problems using [iiwa_stack](https://github.com/IFL-CAMP/iiwa_stack), which is also meant for Kinetic so I think this is not the problem here.

Then I follow the instructions and do the following:
1. Run roscore. For this, I have found that if I just run ```roscore``` the used port is 11311 although I have changed it in the .bashrc, so I execute: 
```
roscore --port 1234
```
2. Run server. 
```
rosrun kuka_controller server_V30032017.py
```
When doing this, the node returns:
```
Starting up on: IP: 172.31.1.50 Port 1234
Error: Connection for KUKA cannot assign requested address: 172.31.1.50 1234
```
3. If after this I run API_ROS_KUKA_V30032017 in the SmartPad it tells:
```
Connecting to server at 172.31.1.50 Port:1234
KUKA iiwa is connected to the server
```
So I guess the connections are well-done and the IIWA is reaching the roscore. However, the server_V30032017.py seems to return some error because the IP/port is already used by the ROS Master, which doesn't make sense at all if I have understood how this works correctly.

I have also tried to run directly the node without launching the roscore, and this time it doesn't return any error, but then I can't read positions from the robot.
1. Run server directly without launching roscore first
```
rosrun kuka_controller server_V30032017.py
```
which this time return no error:
```
Starting up on: IP: 172.31.1.50 Port 1234
Waiting for a connection...
```
2. Run API_ROS_KUKA_V30032017 in the SmartPad returns the same as before:
```
Connecting to server at 172.31.1.50 Port:1234
KUKA iiwa is connected to the server
```
and the server_V30032017.py terminal updates and adds at the end a new line, so now it looks:
```
Starting up on: IP: 172.31.1.50 Port 1234
Waiting for a connection...
Connection from ('172.31.1.147', 180001)
```
3. Run demo for reading current position: 
```
rosrun kuka_controller demo5_ReadData.py
```
which does not return nothing except for the "Sheffield Robotics ... Client Version: V15032017" information box common to all nodes, and I can't see the current robot position. 

Am I doing something wrong? Why can't I launch roscore, and after that, the server node?

Thanks for your help :)

**Comment by lovelyyoshino** [comment]
Hello, I am also studying the iiwa robot. Is your conf.txt file unmodified, and the iiwa robot has not set the master-slave mechanism? I am also studying this, and hope to communicate

**Comment by jonaitken** [comment]
@lovelyyoshino The conf.txt is unmodified, it should be able to be run as is. We've put this version on a variety of iiwas. The master-slave is then set up by IP address - we know the ip of the iiwa itself, and then the app runs on the pendant which then talks to the ROS side which controls the communication.

**Comment by jonaitken** [comment]
@Leytha You can run the rodnode without starting the app on the pendant. Typically when we do it we'll start the app on the pendant, run the rod node and then re-activate app on the pendant and this will establish the communication and you'll see it registered at both ends. If you can my advice is to use 11311 as the port; just to move back to a standard setup!

Once the connection is confirmed you should be able to check the data on the topics; once the connection is confirmed please see if you can echo data.

Also might be worth checking you line:
"esport ROS_WORKSPACE=/home/myuser/catkin_ws" not sure if this is a typo in your question?

**Comment by lovelyyoshino** [comment]
Hello author, if I can, can I know your email, because there is a iiwa in our laboratory, I want to develop it, I have read your code and understood the general idea. But I still don’t have a lot of development experience. I will be grateful if I can get your email. Thank you very much.

**Comment by jonaitken** [comment]
@lovelyyoshino probably the easiest way would be to create a new thread here, and then I can provide what you need!

**Comment by lovelyyoshino** [comment]
Yes, thank you

**Comment by Leytha** [comment]
> Also might be worth checking you line:
> "esport ROS_WORKSPACE=/home/myuser/catkin_ws" not sure if this is a typo in your question?

Yep, that was a typo.

I guess its a problem with using ROS Indigo instead of Kinetic, because I think I have the same setup as yours, except for that. But I cannot change to ROS Kinetic right now and I cannot work with the real robot right now, so I will be trying with ROS Kinetic in a few months and hope it works. I'll let you know if I keep struggling with this. 

Thanks for your answers :)
